version: "3.9"

services:
  api-v1:
    build:
      context: .
      dockerfile: src/api/v1/Dockerfile
    restart: always
    deploy:
      replicas: 3
    networks:
      - backend

  api-v2:
    build:
      context: .
      dockerfile: src/api/v2/Dockerfile
    restart: always
    networks:
      - backend
  
  nginx:
    build: ./deployments/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-v1
      - api-v2
    networks:
      - backend



  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - nginx
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - backend

volumes:
  prometheus_data:
  grafana_data:

networks:
  backend:
    driver: bridge
