version: "3.9"

services:
  api_v1:
    build:
      context: .
      dockerfile: src/api/v1/Dockerfile
    restart: always
    deploy:
      replicas: 3
    networks:
      - backend

  api_v2:
    build:
      context: .
      dockerfile: src/api/v2/Dockerfile
    restart: always
    networks:
      - backend
  
  nginx:
    build: ./deployments/nginx                    # When Dockerfile and nginx.conf are in the same directory
    container_name: nginx
    ports:
      - "80:80" 
      - "443:443"
    depends_on:
      - api_v1
      - api_v2
    networks:
      - backend


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - nginx
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin            # for first creation. Afterwards its saved in the persisten voluumes
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - backend

# after image starts prometheus will scrape the nginx metrics at http://nginx:9113/stub_status

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_container_exporter
    command:
      - --nginx.scrape-uri=http://nginx/stub_status
    ports:
      - '9113:9113'
    depends_on:
      - nginx
    networks:
      - backend



# persistent volumes for prometheus and grafana data on dedicated Docker Folders

volumes:
  prometheus_data:
  grafana_data:

networks:
  backend:
    driver: bridge
