# nginx/nginx.conf

worker_processes auto;          # cpu core control

events {
    worker_connections 1024;    # max number of connections per worker/core
}

http{
    # Rate limiting configuration
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;   # ip client, 10mb of memory, 10 requests per second, api_limit same name as down

    # Upstream
    upstream api_1 {
        server api-v1:8080;
        server api-v1:8080;
        server api-v1:8080;
    }

    upstream api_2 {
        server api-v2:8080;
    }

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server{
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        # Basic Authentication
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/.htpasswd;

        # Rate limiting
        limit_req zone=api_limit burst=20 nodelay;

        location /predict {
            # v1 / v2 testing
            if ($http_x_experiment_group = "debug") {
                proxy_pass http://api_2;
                break;
            }
            proxy_pass http://api_1;
        }        
    }
}